### ISSUE TITLE
> 3 | import __node_cjsModule from 'node:module';

### ISSUE THREAD

**Issue by hanwenbo** [GSTJ/react-native-magic-modal#112]
error: Error: Unable to resolve module node:module from /Users/xxx/node_modules/react-native-magic-modal/dist/index.js: node:module could not be found within the project or in these directories:
  node_modules/react-native-magic-modal/node_modules
  node_modules
  ../../node_modules
  1 | import React, { Fragment, useMemo, memo, useCallback, useEffect, useImperativeHandle } from 'react';
  2 | import { Platform, StyleSheet, Pressable, useWindowDimensions, View, BackHandler } from 'react-native';
> 3 | import __node_cjsModule from 'node:module';

**Comment by jvliwanag** [comment]
This issue appears when using the esm build of react-native-magic-modal which is picked up on expo projects when turning on `unstable_enablePackageExports`.

The esm build itself seems faulty such that it ends up using the `require` from node.

There's only one line of require [here](https://github.com/GSTJ/react-native-magic-modal/blob/07c52cababfa7eda40112e992a0760c047d1cbba/packages/modal/src/components/FullWindowOverlay/FullWindowOverlay.ts#L8).

Since react-native-screens will always be there anyway for all platforms, I wonder if just using a traditional import will be a simpler fix.

A workaround for expo users now while leaving `unstable_enablePackageExports` on is patching this package inverting this package's `package.json`:

```
"exports": {
    "./package.json": "./package.json",
    ".": {
      "require": {
        "types": "./dist/index.d.cts",
        "default": "./dist/index.cjs"
      },
      "import": {
        "types": "./dist/index.d.ts",
        "default": "./dist/index.js"
      }
    }
  },
```

This makes expo pick-up the commonjs version first.

**Comment by GSTJ** [comment]
Thanks for pinpointing! I agree with the solution. Will spin up a quick PR.

**Comment by GSTJ** [comment]
Fixed, let me know if it solves this for you!
