### ISSUE TITLE
Improve the example project

### ISSUE THREAD

**Issue by GSTJ** [GSTJ/react-native-magic-modal#5]
**Is your feature request related to a problem? Please describe.**
The current one isn't too appealing

**Describe the solution you'd like**
One that would better display the capabilities of the project

**Comment by RodSarhan** [comment]
Hello there!
I was very excited to see your medium article as I'm working on a very similar concept in a private work repo.
Our implementations of the imperative modal idea are very similar so I'd be interested in contributing here and sharing ideas and maybe migrate to this instead of maintaining my own implementation.
If that sounds good to you please let me know your preferred method of contact, and which parts of the code you can use my help in. Cheers!

**Comment by GSTJ** [comment]
Hi Roudain! That's awesome; I will gladly support you guys with the
package. Also, I'm here for you guys if you need help migrating.

Regarding ways to contribute, I do have a few in mind that could use some
help:

1 - Making an improved modal Queue system while maintaining the async/await
logic working.
Currently, it can only put a single modal in the queue if necessary. An
application will hardly try to show three modals simultaneously, so I
didn't give it a priority, but regardless it could happen in some specific
uses.

2 - Porting it over to work with React web too.
It would require creating a .web file with another modal solution other
than react-native-modal. The more complicated part would be making sure
props are compatible between both.

3 - Making the Changelog more robust
Currently, even if I release a doc change, for the most part, it still
registers a new release on the Changelog, taking up a lot of space but
empty. Ideally, we could 'merge' those releases that changed little to
nothing or think about a better solution.

I'm also open to hearing your ideas. The changes above are in no way a list
of obligations, but if you feel like so, I would appreciate a hand.

You can reach me directly via email at ***@***.***
Here's also my Discord in case you need it: Taveira#0899

Em sáb., 6 de ago. de 2022 às 06:51, Roudain Sarhan <
***@***.***> escreveu:
